### PR TITLE
 i change the hover color on resume button and contact page box border

### PR DESCRIPTION
**Pull request by dipakja**

### CODE REVIEW

**Comment by dipakja** [comment]
small change

**Comment by Monson2002** [comment]
You have made the user experience even worse, the button text is not even visible until you hover over it.

**Comment by dipakja** [comment]
This is my first PR and I don't have that much experience about it.  You don't have to say harshly. Next time I will do much better. Thank you for your review. **Thank you ** Again. I will remember your review throughout my contribution time period.

**Comment by dipakja** [comment]
If I started lately, it doesn't mean that I won't make it big. But I promise I will make much better than you.

**Pull request closed without merging**
